import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "../components/Header";
import Home from "../components/Home";

const index: NextPage = () => {
  const [model, setModel] = useState<boolean>(false);
  const [search, setSearch] = useState<string>("");

  return (
    <div className="container mx-auto overflow-x-hidden">
      <Head>
        <title>Next Tailwind TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header search={search} setSearch={setSearch} setModel={setModel} />
      <Home search={search} model={model} setModel={setModel} />
    </div>
  );
};

export default index;
